# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

#pipelines >> stages >> jobs >> tasks/steps

jobs:
- job: job1
  steps:
  - script: echo Job1 Hello, world changed!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: job2
  dependsOn: job1
  steps:
    - script: echo job2
  displayName: 'Job2 Script'
- job: job3
  dependsOn: job2
  steps:
    - script: echo Hello job3
  displayName: 'Job3 Script'
- job: job4
  dependsOn: 
  - job2
  - job3
  steps:
    - script: echo Hello job4
  displayName: 'Job4 Script'