# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
    - bash: echo ls -R $(System.DefaultWorkingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: echo ls -R $(Build.ArtifactStagingDirectory)
# - stage: DevDeploy
#   dependsOn: build
#   jobs:
#   - job: DevDeploy
#     steps:
#     - bash: echo build DevDeploy
# - stage: QADeploy
#   dependsOn: build
#   jobs:
#   - job: QADeploy
#     steps:
#     - bash: echo build QADeploy
# - stage: ProdDeploy
#   dependsOn:
#     - DevDeploy
#     - QADeploy
#   jobs:
#   - job: ProdDeploy
#     steps:
#     - bash: echo build ProdDeploy
