# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# strategy:
#  matrix:
#    linux:
#      operatingSystem: 'ubuntu-latest'
#    mac:
#      operatingSystem: 'macos-latest'
pool:
  vmImage: $(operatingSystem)

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo Build job
- stage: DevDeploy
  jobs:
  - deployment:
    environment: Dev 
    strategy:
     runOnce:
       deploy:
         steps:
           - bash: echo this is first pipeline for Dev
- stage: QADeploy
  jobs:
  - deployment:
    environment: QA 
    strategy:
     runOnce:
       deploy:
         steps:
           - bash: echo this is first pipeline for QA